<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
	$routeName      = $requestInterface->getRouteName();
	$moduleName     = $requestInterface->getModuleName(); 
	$controllerName = $requestInterface->getControllerName(); 
	$actionName     = $requestInterface->getActionName();
?>
<?php if($routeName == 'cms' &&  $controllerName == 'index') : ?>
	<div class="commonfinder">
<?php endif; ?>
<div class="quickfind-wrapper">
<form class="quickfind"
      action="#"
      id="quickfind-form"
      method="post">
	  
	   <div class="form-list">
			<div class="fields">
			  <div class="field">
				<label class="label" for="type_of_cruises"><span><?php echo __('TYPE OF CRUISES'); ?></span></label>
				<div class="control">
					<select name="type_of_cruises" id="type_of_cruises">
							<option value="">SELECT CRUISES</option>
							<option value="luxury-cruises">Syd Luxury Cruises</option>
							<option value="dinner-cruises">Syd Dinner Cruises</option>
							<option value="lunch-cruises">Syd Lunch Cruises</option>
							<option value="breakfast-high-tea">Syd Breakfast &amp; High Tea</option>
							<option value="sightseeing-cruises">Syd Sightseeing Cruises</option>
							<option value="hop-on-hop-off">Syd Hop On Hop Off</option>
					</select>
			    </div>
			  </div>
				
			  <div class="field">
				<label class="label" for="date_of_cruises"><span><?php echo __('Date'); ?></span></label>
				<div class="control">
					<input type="text" name="date_of_cruises" id="date_of_cruises">
			    </div>
			  </div>
				
			  <div class="field">
				<label class="label" for="adult"><span><?php echo __('ADULT'); ?></span></label>
				<div class="control">
					<select name="adult" id="adult">
							<option value="0">Adults</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
							<option value="8">8</option>
							<option value="9">9</option>
							<option value="10">10</option>
							<option value="11">11</option>
							<option value="12">12</option>
							<option value="13">13</option>
							<option value="14">14</option>
							<option value="15">15</option>
							<option value="16">16</option>
							<option value="17">17</option>
							<option value="18">18</option>
							<option value="19">19</option>
							<option value="20">20</option>
							<option value="21">21</option>
							<option value="22">22</option>
							<option value="23">23</option>
							<option value="24">24</option>
							<option value="25">25</option>
							<option value="26">26</option>
							<option value="27">27</option>
							<option value="28">28</option>
							<option value="29">29</option>
							<option value="30">30</option>
							<option value="31">31</option>
							<option value="32">32</option>
							<option value="33">33</option>
							<option value="34">34</option>
							<option value="35">35</option>
							<option value="36">36</option>
							<option value="37">37</option>
							<option value="38">38</option>
							<option value="39">39</option>
							<option value="40">40</option>
							<option value="41">41</option>
							<option value="42">42</option>
							<option value="43">43</option>
							<option value="44">44</option>
							<option value="45">45</option>
							<option value="46">46</option>
							<option value="47">47</option>
							<option value="48">48</option>
							<option value="49">49</option>
							<option value="50">50</option>
							<option value="51">51</option>
							<option value="52">52</option>
							<option value="53">53</option>
							<option value="54">54</option>
							<option value="55">55</option>
							<option value="56">56</option>
							<option value="57">57</option>
							<option value="58">58</option>
							<option value="59">59</option>
							<option value="60">60</option>
							<option value="61">61</option>
							<option value="62">62</option>
							<option value="63">63</option>
							<option value="64">64</option>
							<option value="65">65</option>
							<option value="66">66</option>
							<option value="67">67</option>
							<option value="68">68</option>
							<option value="69">69</option>
							<option value="70">70</option>
							<option value="71">71</option>
							<option value="72">72</option>
							<option value="73">73</option>
							<option value="74">74</option>
							<option value="75">75</option>
							<option value="76">76</option>
							<option value="77">77</option>
							<option value="78">78</option>
							<option value="79">79</option>
							<option value="80">80</option>
							<option value="81">81</option>
							<option value="82">82</option>
							<option value="83">83</option>
							<option value="84">84</option>
							<option value="85">85</option>
							<option value="86">86</option>
							<option value="87">87</option>
							<option value="88">88</option>
							<option value="89">89</option>
							<option value="90">90</option>
							<option value="91">91</option>
							<option value="92">92</option>
							<option value="93">93</option>
							<option value="94">94</option>
							<option value="95">95</option>
							<option value="96">96</option>
							<option value="97">97</option>
							<option value="98">98</option>
<option value="99">99</option>
					</select>
			    </div>
			  </div>	
				
			  <div class="field">
				<label class="label" for="children"><span><?php echo __('CHILDREN'); ?></span></label>
				<div class="control">
					<select name="children" id="children">
							<option value="0">Children</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
							<option value="8">8</option>
							<option value="9">9</option>
							<option value="10">10</option>
							<option value="11">11</option>
							<option value="12">12</option>
							<option value="13">13</option>
							<option value="14">14</option>
							<option value="15">15</option>
							<option value="16">16</option>
							<option value="17">17</option>
							<option value="18">18</option>
							<option value="19">19</option>
							<option value="20">20</option>
							<option value="21">21</option>
							<option value="22">22</option>
							<option value="23">23</option>
							<option value="24">24</option>
							<option value="25">25</option>
							<option value="26">26</option>
							<option value="27">27</option>
							<option value="28">28</option>
							<option value="29">29</option>
							<option value="30">30</option>
							<option value="31">31</option>
							<option value="32">32</option>
							<option value="33">33</option>
							<option value="34">34</option>
							<option value="35">35</option>
							<option value="36">36</option>
							<option value="37">37</option>
							<option value="38">38</option>
							<option value="39">39</option>
							<option value="40">40</option>
							<option value="41">41</option>
							<option value="42">42</option>
							<option value="43">43</option>
							<option value="44">44</option>
							<option value="45">45</option>
							<option value="46">46</option>
							<option value="47">47</option>
							<option value="48">48</option>
							<option value="49">49</option>
							<option value="50">50</option>
							<option value="51">51</option>
							<option value="52">52</option>
							<option value="53">53</option>
							<option value="54">54</option>
							<option value="55">55</option>
							<option value="56">56</option>
							<option value="57">57</option>
							<option value="58">58</option>
							<option value="59">59</option>
							<option value="60">60</option>
							<option value="61">61</option>
							<option value="62">62</option>
							<option value="63">63</option>
							<option value="64">64</option>
							<option value="65">65</option>
							<option value="66">66</option>
							<option value="67">67</option>
							<option value="68">68</option>
							<option value="69">69</option>
							<option value="70">70</option>
							<option value="71">71</option>
							<option value="72">72</option>
							<option value="73">73</option>
							<option value="74">74</option>
							<option value="75">75</option>
							<option value="76">76</option>
							<option value="77">77</option>
							<option value="78">78</option>
							<option value="79">79</option>
							<option value="80">80</option>
							<option value="81">81</option>
							<option value="82">82</option>
							<option value="83">83</option>
							<option value="84">84</option>
							<option value="85">85</option>
							<option value="86">86</option>
							<option value="87">87</option>
							<option value="88">88</option>
							<option value="89">89</option>
							<option value="90">90</option>
							<option value="91">91</option>
							<option value="92">92</option>
							<option value="93">93</option>
							<option value="94">94</option>
							<option value="95">95</option>
							<option value="96">96</option>
							<option value="97">97</option>
							<option value="98">98</option>
							<option value="99">99</option>

					</select>
			    </div>
			  </div>	
				
				<div class="field">
				  <div class="control">		
					<!--<input type="submit" name="submit" value="search"/>-->
                    <button class="action primary"><span><span>Search</span></span></button>
				  </div>
				</div>
				
   	 		</div>
	   </div>
</form>
</div>
<?php if($routeName == 'cms' &&  $controllerName == 'index') : ?>
	</div>
<?php endif; ?>

<script type="text/javascript">
require(["jquery", "jquery/ui"], function (jq) {
	jq(document).ready(function () {
		var currentDate = new Date();
		var year = currentDate.getFullYear();
		var month = currentDate.getMonth();
		var day = currentDate.getDate();
		var self = this;
		jq("#date_of_cruises").datepicker( 
			{ 
				dateFormat: "d/m/yy",
				controlType: 'select',
				timeFormat: 'HH:mm TT',
				showTime: false,
				minDate: new Date(year, month, day, '00', '00', '00', '00'),
				beforeShowDay: self.disableDate
			} 
		);
		jq(".ui-datepicker-trigger").removeAttr("style");
		jq(".ui-datepicker-trigger").click(function(){
			jq('#date_of_cruises').focus();
		});  
	});
});
</script>